version: '3.8'
services:
  proxy:
    build: ../../dsf-docker/bpe_proxy
    image: datasharingframework/bpe_proxy
    restart: "no"
    ports:
      - 127.0.0.1:8080:80
      - 127.0.0.1:8443:443
    secrets:
      - bpe.crt
      - bpe.key.plain
      - issuing_ca.crt
      - ca_chain.crt
    environment:
      TZ: Europe/Berlin
      HTTPS_SERVER_NAME_PORT: localhost:443
      APP_SERVER_IP: 172.28.1.27
      SSL_CERTIFICATE_FILE: /run/secrets/bpe.crt
      SSL_CERTIFICATE_KEY_FILE: /run/secrets/bpe.key.plain
      SSL_CERTIFICATE_CHAIN_FILE: /run/secrets/issuing_ca.crt
      SSL_CA_CERTIFICATE_FILE: /run/secrets/ca_chain.crt
      SSL_CA_DN_REQUEST_FILE: /run/secrets/issuing_ca.crt
      SSL_EXPECTED_CLIENT_I_DN_CN_VALUES: "'DSF Dev Issuing CA'"
    networks:
      frontend:
        ipv4_address: 172.28.1.26
    depends_on:
      - app

  app:
    build: ../../dsf-bpe/dsf-bpe-server-jetty/docker
    image: datasharingframework/bpe
    restart: "no"
    ports:
      - 127.0.0.1:5002:5002
    secrets:
      - db_liquibase.password
      - db_user.password
      - db_user_camunda.password
      - root_ca.crt
      - bpe.crt
      - bpe.key
      - ca_chain.crt
    volumes:
      - type: bind
        source: ./process
        target: /opt/bpe/process
        read_only: true
      - type: bind
        source: ./log
        target: /opt/bpe/log
    environment:
      TZ: Europe/Berlin
      EXTRA_JVM_ARGS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5002
      DEV_DSF_LOG_DATA_FILE_ENABLED: 'true'
      DEV_DSF_BPE_DB_URL: jdbc:postgresql://db/bpe
      DEV_DSF_BPE_DB_LIQUIBASE_PASSWORD_FILE: /run/secrets/db_liquibase.password
      DEV_DSF_BPE_DB_USER_PASSWORD_FILE: /run/secrets/db_user.password
      DEV_DSF_BPE_DB_USER_CAMUNDA_PASSWORD_FILE: /run/secrets/db_user_camunda.password
      DEV_DSF_BPE_FHIR_CLIENT_TRUST_SERVER_CERTIFICATE_CAS: /run/secrets/root_ca.crt
      DEV_DSF_BPE_FHIR_CLIENT_CERTIFICATE: /run/secrets/bpe.crt
      DEV_DSF_BPE_FHIR_CLIENT_CERTIFICATE_PRIVATE_KEY: /run/secrets/bpe.key
      DEV_DSF_BPE_FHIR_CLIENT_CERTIFICATE_PRIVATE_KEY_PASSWORD: 'password'
      DEV_DSF_BPE_SERVER_UI_THEME: dev
      DEV_DSF_BPE_SERVER_BASE_URL: https://bpe:8443/bpe
      DEV_DSF_BPE_FHIR_SERVER_BASE_URL: https://fhir/fhir
      DEV_DSF_BPE_SERVER_ROLECONFIG: |
        - webbrowser_test_user:
            thumbprint: ${WEBBROWSER_TEST_USER_THUMBPRINT}
            dsf-role:
              - ADMIN
      DEV_DSF_SERVER_AUTH_TRUST_CLIENT_CERTIFICATE_CAS: /run/secrets/ca_chain.crt
    networks:
      frontend:
        ipv4_address: 172.28.1.27
      backend:
        ipv4_address: 172.28.1.34
      fhir_bpe:
        ipv4_address: 172.28.1.3
    depends_on:
      - db

  db:
    image: postgres:15
    restart: "no"
#    ports:
#      - 127.0.0.1:5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U liquibase_user -d bpe"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      TZ: Europe/Berlin
      POSTGRES_PASSWORD_FILE: /run/secrets/db_liquibase.password
      POSTGRES_USER: liquibase_user
      POSTGRES_DB: bpe
    networks:
      backend:
        ipv4_address: 172.28.1.35
    secrets:
      - db_liquibase.password

secrets:
  bpe.crt:
    file: ./secrets/bpe.crt
  bpe.key:
    file: ./secrets/bpe.key
  bpe.key.plain:
    file: ./secrets/bpe.key.plain
  issuing_ca.crt:
    file: ./secrets/issuing_ca.crt
  root_ca.crt:
    file: ./secrets/root_ca.crt
  ca_chain.crt:
    file: ./secrets/ca_chain.crt

  db_liquibase.password:
    file: ./secrets/db_liquibase.password
  db_user.password:
    file: ./secrets/db_user.password
  db_user_camunda.password:
    file: ./secrets/db_user_camunda.password

networks:
  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.1.24/29
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.1.32/29
  fhir_bpe:
    external: true