---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dsf-ssl-cert
data:
  ssl_certificate_file.pem: |
    -----BEGIN CERTIFICATE-----
    MIIFazCCA1OgAwIBAgIRAIIQz7DSQONZRGPgu2OCiwAwDQYJKoZIhvcNAQELBQAw
    ...
    -----END CERTIFICATE-----
  ssl_certificate_chain_file.pem: |
    -----BEGIN CERTIFICATE-----
    ...
    -----END CERTIFICATE-----
  ssl_certificate_key_file.pem: |
    -----BEGIN CERTIFICATE-----
    ...
    -----END CERTIFICATE-----
