apiVersion: v1
kind: ConfigMap
metadata:
  name: dsf-client-cert
data:
  client_certificate.pem: |
    -----BEGIN CERTIFICATE-----
    MIIFazCCA1OgAwIBAgIRAIIQz7DSQONZRGPgu2OCiwAwDQYJKoZIhvcNAQELBQAw
    ...
    -----END CERTIFICATE-----
  client_certificate_private_key.pem: |
    -----BEGIN CERTIFICATE-----
    ...
    -----END CERTIFICATE-----
  client_certificate_private_key.pem.password: "dein-passwort"
