---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dsf-fhir-config
data:
  TZ: "Europe/Berlin"
  DEV_DSF_FHIR_DB_URL: "jdbc:postgresql://dsf-db/fhir"
  DEV_DSF_FHIR_DB_LIQUIBASE_PASSWORD_FILE: "/run/secrets/db/db_liquibase.password"
  DEV_DSF_FHIR_DB_USER_PASSWORD_FILE: "/run/secrets/db/db_user.password"
  DEV_DSF_FHIR_DB_USER_PERMANENT_DELETE_PASSWORD_FILE: "/run/secrets/db/db_user_permanent_delete.password"
  DEV_DSF_FHIR_CLIENT_CERTIFICATE: "/run/secrets/cert/client_certificate.pem"
  DEV_DSF_FHIR_CLIENT_CERTIFICATE_PRIVATE_KEY: "/run/secrets/cert/client_certificate_private_key.pem"
  DEV_DSF_FHIR_CLIENT_CERTIFICATE_PRIVATE_KEY_PASSWORD_FILE: "/run/secrets/cert/client_certificate_private_key.pem.password"
  DEV_DSF_FHIR_SERVER_ORGANIZATION_IDENTIFIER_VALUE: "todo.organization.com"
  # TODO specify the base url of this DSF FHIR server
  DEV_DSF_FHIR_SERVER_BASE_URL: "https://dsf.todo.organization.com/fhir"
  # TODO specify the SHA-512 thumbprint of the Client-Certificate as lower case HEX (Regex: ^[a-f0-9]{128}$)
  # certtool --fingerprint --hash=sha512 --infile=client_certificate.pem
  # or simply get it from allowlist management tool
  DEV_DSF_FHIR_SERVER_ORGANIZATION_THUMBPRINT: ""
  # TODO specify role configuration to allow access to the UI via web-browser or REST API for specific users, see documentation at dsf.dev
  DEV_DSF_FHIR_SERVER_ROLECONFIG: |
    ""
---
apiVersion: v1
kind: Pod
metadata:
  name: dsf-app
  labels:
    app: dsf-app-pod
spec:
  restartPolicy: OnFailure
  containers:
    - name: dsf-app
      image: ghcr.io/datasharingframework/fhir:2.1.0
      envFrom:
        - configMapRef:
            name: dsf-fhir-config
      volumeMounts:
        - mountPath: /opt/fhir/log
          name: fhir-log
        - name: db-passwords
          mountPath: /run/secrets/db
          readOnly: true
        - name: client-cert
          mountPath: /run/secrets/cert
          readOnly: true

  volumes:
    - name: fhir-log
      hostPath:
        path: /home/podman/.local/state/dsf/fhir/log
        type: Directory
    - name: db-passwords
      secret:
        secretName: dsf-fhir-passwords
    - name: client-cert
      configMap:
        name: dsf-client-cert
