---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dsf-bpe-cache
  annotations:
    volume.podman.io/uid: "0"
    volume.podman.io/gid: "2202"
    volume.podman.io/mount-options: "uid=0,gid=2202,mode=0770"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dsf-bpe-config
data:
  TZ: "Europe/Berlin"
  DEV_DSF_BPE_DB_URL: "jdbc:postgresql://dsf-bpe-db/bpe"
  DEV_DSF_BPE_DB_LIQUIBASE_PASSWORD_FILE: "/run/secrets/db/db_liquibase.password"
  DEV_DSF_BPE_DB_USER_PASSWORD_FILE: "/run/secrets/db/db_user.password"
  DEV_DSF_BPE_DB_USER_ENGINE_PASSWORD_FILE: "/run/secrets/db/db_user_camunda.password"
  DEV_DSF_BPE_FHIR_CLIENT_CERTIFICATE: "/run/secrets/cert/client_certificate.pem"
  DEV_DSF_BPE_FHIR_CLIENT_CERTIFICATE_PRIVATE_KEY: "/run/secrets/cert/client_certificate_private_key.pem"
  DEV_DSF_BPE_FHIR_CLIENT_CERTIFICATE_PRIVATE_KEY_PASSWORD_FILE: "/run/secrets/cert/client_certificate_private_key.pem.password"
  # TODO specify the base url of this DSF FHIR server
  DEV_DSF_BPE_FHIR_SERVER_BASE_URL: "https://dsf.todo.organization.com/fhir"
  # DEV_DSF_BPE_PROCESS_EXCLUDED: |
  #   dsfdev_updateAllowList|1.0
---
apiVersion: v1
kind: Pod
metadata:
  name: dsf-bpe-app
  labels:
    app: dsf-bpe-app
spec:
  restartPolicy: OnFailure
  containers:
    - name: dsf-bpe-app
      image: ghcr.io/datasharingframework/bpe:2.1.0
      envFrom:
        - configMapRef:
            name: dsf-bpe-config
      volumeMounts:
        - name: db-passwords
          mountPath: /run/secrets/db
          readOnly: true
        - name: client-cert
          mountPath: /run/secrets/cert
          readOnly: true
        - name: bpe-log
          mountPath: /opt/bpe/log
        - name: bpe-process
          mountPath: /opt/bpe/process
          readOnly: true
        - name: bpe-cache
          mountPath: /opt/bpe/cache
  volumes:
    - name: bpe-log
      hostPath:
        path: /home/podman/.local/state/dsf/bpe/log
        type: Directory
    - name: bpe-process
      hostPath:
        path: /home/podman/.config/dsf-bpe/process
        type: Directory
    - name: db-passwords
      secret:
        secretName: dsf-bpe-passwords
    - name: client-cert
      configMap:
        name: dsf-client-cert
    - name: bpe-cache
      persistentVolumeClaim:
        claimName: dsf-bpe-cache
