package dev.dsf.bpe.start;

public interface ConstantsExampleStarters
{
	String ENV_DSF_CLIENT_CERTIFICATE_PATH = "DSF_CLIENT_CERTIFICATE_PATH";
	String ENV_DSF_CLIENT_CERTIFICATE_PASSWORD = "DSF_CLIENT_CERTIFICATE_PASSWORD";

	String NAMINGSYSTEM_DSF_ORGANIZATION_IDENTIFIER_VALUE_CONSORTIUM_HIGHMED = "highmed.org";
	String NAMINGSYSTEM_DSF_ORGANIZATION_IDENTIFIER_VALUE_CONSORTIUM_MII = "medizininformatik-initiative.de";
	String NAMINGSYSTEM_DSF_ORGANIZATION_IDENTIFIER_VALUE_CONSORTIUM_NUM = "netzwerk-universitaetsmedizin.de";

	String TTP_FHIR_BASE_URL = "https://ttp/fhir/";
	String NAMINGSYSTEM_DSF_ORGANIZATION_IDENTIFIER_VALUE_TTP = "Test_TTP";

	String DIC_1_FHIR_BASE_URL = "https://dic1/fhir/";
	String NAMINGSYSTEM_DSF_ORGANIZATION_IDENTIFIER_VALUE_DIC_1 = "Test_DIC_1";

	String DIC_2_FHIR_BASE_URL = "https://dic2/fhir/";
	String NAMINGSYSTEM_DSF_ORGANIZATION_IDENTIFIER_VALUE_DIC_2 = "Test_DIC_2";

	String DIC_3_FHIR_BASE_URL = "https://dic3/fhir/";
	String NAMINGSYSTEM_DSF_ORGANIZATION_IDENTIFIER_VALUE_DIC_3 = "Test_DIC_3";
}
